### PR TITLE
[add] reviewdog

### PR DESCRIPTION
**Pull request by kazukazuinaina**
Hello maintainer!
I added new test to check Vim script's syntax.
This unit test use `github actions` and [reviewdog](https://github.com/reviewdog/action-vint).
Could you check this Pull Request?
If you don't need this pull request, feel free to close it. 🙇

## reference

> https://github.com/reviewdog/action-vint

### CODE REVIEW

**Comment by kazukazuinaina** [comment]
This CI will work when merged!

**Comment by kazukazuinaina** [comment]
ping @benknoble

**Comment by kazukazuinaina** [comment]
If you don't need this patch, feel free to close it.

**Comment by benknoble** [comment]
@dsifford any thoughts?

**Comment by dsifford** [comment]
Not sure there's exactly a _need_ for this as the repo is relatively stable and changes have been tiny over the last year or so. I realize that it's a pretty minimal add, but not sure I want to be responsible for keeping the action version up to date.

That said, I have no strong feelings either way.

**Comment by benknoble** [comment]
That pretty much sums of my reaction too: no strong need, and I don’t want to maintain it or have it get in the way.

That said, I’m not super familiar with what types of things vint can help us catch...

**Comment by zenorocha** [comment]
+1 for keeping it lean and with a reduced number of dependencies

**Comment by dsifford** [comment]
Okay, let's just close this for now then.

Thanks for the PR nevertheless @kazukazuinaina.

**Comment by kazukazuinaina** [comment]
Ok, I got it.
Thanks for review my PR

**Pull request closed without merging**
