### PR TITLE
A better contrast for the tabline background

### PR DESCRIPTION
**Pull request by SlyBouhafs**
Here are two screenshots, the first one is the new setting and the second one is the old setting.
Screen Shot 2021-09-02 at 00 47 57
Screen Shot 2021-09-02 at 00 17 41

### CODE REVIEW

**Comment by benknoble** [comment]
I don't have any issue with the change, but it looks like there's a spurious commit there: We don't need the "merge PR commit," just the change.

**Comment by SlyBouhafs** [comment]
@benknoble Well, i'm not sure how to remove that merge PR commit, should i just do another PR?

**Comment by dsifford** [comment]
@benknoble if you're cool with the change just do a squash merge and that stray commit won't matter.

**Comment by benknoble** [comment]
Hm, I think I'll just cherry-pick it myself tomorrow. Don't worry about it @SlyBouhafs , I'll get it fixed up.

**Pull request closed without merging**
