### PR TITLE
(improvement) add dracula bold schema

### PR DESCRIPTION
**Pull request by guilhermehubner**
This theme is my version of dracula theme. The only change is that I
decided to highlight some special words to have a better experience
using this beautiful theme

### CODE REVIEW

**Comment by benknoble** [comment]
@guilhermehubner That's awesome that you put that together!

At this time, I'm not sure if dracula/vim is considering new vim colorschemes. I see you've got a fork of the repo—you could consider maintaining this there? Or, you could request via the main dracula repo to have a new theme added (vim-bold) or some such?

I'm glad to hear you like the color scheme!

Feedback @dsifford ?

**Comment by guilhermehubner** [comment]
@benknoble I don't know if it would be a good thing to maintain it on my fork because it is really a dracula copy with some "improvements". Maybe I didn't explained well what I did, I'll try again. I only put some bold in some words that I thought should be highlighted ( I came from `molokai` theme );

I didn't changed any color.

Maybe it would be an option to merge it in actual theme?

I liked the idea of `vim-bold` as well.

Here is the diff:

```diff
diff --git a/colors/dracula.vim b/colors/dracula.vim
index f62a18a..fdcb1c1 100644
--- a/colors/dracula.vim
+++ b/colors/dracula.vim
@@ -11,6 +11,7 @@
 " @author Éverton Ribeiro <nuxlli@gmail.com>
 " @author Derek Sifford <dereksifford@gmail.com>
 " @author Zeno Rocha <hi@zenorocha.com>
+" @author Guilherme Hübner <guilhermehubner@gmail.com>
 scriptencoding utf8
 " }}}
 
@@ -23,7 +24,7 @@ if v:version > 580
   endif
 endif
 
-let g:colors_name = 'dracula'
+let g:colors_name = 'dracula_bold'
 
 if !(has('termguicolors') && &termguicolors) && !has('gui_running') && &t_Co != 256
   finish
@@ -150,6 +151,7 @@ call s:h('DraculaSelection', s:none, s:selection)
 call s:h('DraculaSubtle', s:subtle)
 
 call s:h('DraculaCyan', s:cyan)
+call s:h('DraculaCyanBold', s:cyan, s:none, [s:attrs.bold])
 call s:h('DraculaCyanItalic', s:cyan, s:none, [s:attrs.italic])
 
 call s:h('DraculaGreen', s:green)
@@ -164,6 +166,7 @@ call s:h('DraculaOrangeBoldItalic', s:orange, s:none, [s:attrs.bold, s:attrs.ita
 call s:h('DraculaOrangeInverse', s:bg, s:orange)
 
 call s:h('DraculaPink', s:pink)
+call s:h('DraculaPinkBold', s:pink, s:none, [s:attrs.bold])
 call s:h('DraculaPinkItalic', s:pink, s:none, [s:attrs.italic])
 
 call s:h('DraculaPurple', s:purple)
@@ -171,9 +174,11 @@ call s:h('DraculaPurpleBold', s:purple, s:none, [s:attrs.bold])
 call s:h('DraculaPurpleItalic', s:purple, s:none, [s:attrs.italic])
 
 call s:h('DraculaRed', s:red)
+call s:h('DraculaRedBold', s:red, s:none, [s:attrs.bold])
 call s:h('DraculaRedInverse', s:fg, s:red)
 
 call s:h('DraculaYellow', s:yellow)
+call s:h('DraculaYellowBold', s:yellow, s:none, [s:attrs.bold])
 call s:h('DraculaYellowItalic', s:yellow, s:none, [s:attrs.italic])
 
 call s:h('DraculaError', s:red, s:none, [], s:red)
@@ -244,7 +249,7 @@ hi! link WarningMsg   DraculaOrangeInverse
 " Syntax: {{{
 
 " Required as some plugins will overwrite
-call s:h('MatchParen', s:green, s:none, [s:attrs.underline])
+call s:h('MatchParen', s:green, s:none, [s:attrs.underline,s:attrs.bold])
 call s:h('Conceal', s:cyan, s:none)
 
 " Neovim uses SpecialKey for escape characters only. Vim uses it for that, plus whitespace.
@@ -264,29 +269,29 @@ hi! link SpellLocal DraculaWarnLine
 hi! link SpellCap DraculaInfoLine
 hi! link SpellRare DraculaInfoLine
 
-hi! link Constant DraculaPurple
+hi! link Constant DraculaPurpleBold
 hi! link String DraculaYellow
 hi! link Character DraculaPink
 hi! link Number Constant
 hi! link Boolean Constant
 hi! link Float Constant
 
-hi! link Identifier DraculaFg
+hi! link Identifier DraculaGreen
 hi! link Function DraculaGreen
 
-hi! link Statement DraculaPink
-hi! link Conditional DraculaPink
-hi! link Repeat DraculaPink
+hi! link Statement DraculaPinkBold
+hi! link Conditional DraculaPinkBold
+hi! link Repeat DraculaPinkBold
 hi! link Label DraculaPink
 hi! link Operator DraculaPink
-hi! link Keyword DraculaPink
-hi! link Exception DraculaPink
+hi! link Keyword DraculaPinkBold
+hi! link Exception DraculaPinkBold
 
 hi! link PreProc DraculaPink
 hi! link Include DraculaPink
 hi! link Define DraculaPink
 hi! link Macro DraculaPink
-hi! link PreCondit DraculaPink
+hi! link PreCondit DraculaPinkBold
 hi! link StorageClass DraculaPink
 hi! link Structure DraculaPink
 hi! link Typedef DraculaPink
```

As you can see it is pretty much the same theme;

**Comment by benknoble** [comment]
Indeed, I've looked at the diff.

dsifford maintains a [dracula theme spec](https://dsifford.github.io/dracula-spec/), which this would not adhere to (though, AFAIK, required adherence to the spec is rather loose).

I would be happy to leave a link to your version on this repo; I'm just not sure it makes sense for us to spend our time maintaining duplicate code.

**Comment by dsifford** [comment]
Agree with @benknoble. We have to be careful about merging stuff like this (however small it may be) because it could potentially open a floodgate of others adding small adjustments/flags/options and lead to a difficult codebase to maintain overall.

The code here is MIT so feel free to maintain a fork with the code changes. That's fine by us!

**Comment by guilhermehubner** [comment]
You guys are right, maybe it wouldn't be a good thing to add "duplicated" code in this repo. I'll change my fork name to dracula-vim and keep it there. Thank you guys for the good work maintaining this awesome color schema! Hope a day I can contribute effectively with it!

Feel free to close this PR

**Pull request closed without merging**
